name = input('What is your name?\n')
print('Welcome, ' + name)
print()
print('For the next series of questions, please type your answers in figures only!\n')
hours = int(input('How many hours have you worked so far?\n'))
rate = float(input('At what rate per hour did you work for?\n'))
print('This is what you will be paid at the end of the week!\n')
pay = round((hours)*(rate))
print('Total pay')
print('$' + str((pay)))
